# Generated by Django 5.0.6 on 2024-06-18 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(default='', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('boleta', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('plan', models.IntegerField()),
                ('asunto', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=350)),
            ],
        ),
    ]
