# Generated by Django 5.0.6 on 2024-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionInformatica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_origen', models.CharField(max_length=200)),
                ('carrera_origen', models.CharField(max_length=200)),
                ('codigo_origen', models.CharField(max_length=50)),
                ('nombre_origen', models.CharField(max_length=200)),
                ('plan_destino', models.CharField(max_length=200)),
                ('carrera_destino', models.CharField(max_length=200)),
                ('codigo_destino', models.CharField(max_length=50)),
                ('nombre_destino', models.CharField(max_length=200)),
            ],
        ),
    ]
