# Generated by Django 5.0.7 on 2024-08-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionInformatica', '0002_equivalencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrePlanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('equivalencia', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equivalencias2010',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('equivalencia', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equivalencias2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('equivalencia', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Equivalencia',
        ),
    ]
