# Generated by Django 5.0.7 on 2024-09-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionInformatica', '0003_entreplanes_equivalencias2010_equivalencias2021_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='boleta',
            field=models.BigIntegerField(),
        ),
    ]
