# Generated by Django 5.0.7 on 2024-09-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionInformatica', '0004_alter_alumno_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
