# Generated by Django 5.0.7 on 2024-09-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionInformatica', '0005_alter_alumno_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
